export default {
	width: 200,
	height: 200,
	baseColor: '#4095bf',
	lineColor: '#4095bf',
	titleColor: '#1d3940',
	highlightColor: '#884ca1',
	donutColor: 'white',
	legendDataType: 'value',
	legendColor: '#1d3940',
	orientation: 0,
	circleArea: 1,
	className: '',
	style: {},
	secondaryColor: '#e9ecef',
	innerBackgroundColor: '#c8d1d4',
	outerBackgroundColor: '#dee6e8',
	overlayDataType: 'value',
	overlayColor: '#1d3940',
	averageType: 'averageValueWithUnit',
	lineWidth: 20,
	barWidth: 10,
	slice: 0
}